---
# More about feed: https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/
name: Build image for BPi-R4 with MTK feed

on:
  workflow_dispatch:
    inputs:
      DEVICE_CONFIG:
        description: "Device configuration selection: <none> or poe (default: non-poe)"
        required: true
        type: choice
        default: 'non-poe'
        options:
          # - poe
          - non-poe

env:
  REMOTE_REPOSITORY: danpawlik/bpi-r4-mtk
  REMOTE_BRANCH: main
  # OpenWrt
  OPENWRT_REPOSITORY: https://github.com/openwrt/openwrt
  OPENWRT_REF: 68bf4844a1cbc9f404f6e93b70a2657e74f1dce9
  # Mediatek Feed
  MEDIATEK_REPOSITORY: https://git01.mediatek.com/openwrt/feeds/mtk-openwrt-feeds
  MEDIATEK_REF: 42df09d4cf568c795e71427668fae0eea4f112c5
  # Configuration
  RELEASE_PREFIX: bpi-r4-mtk
  DEVICE_CONFIG: ${{ inputs.DEVICE_CONFIG == 'poe' && 'configs/mediatek/mt7988a/bpi-r4-poe' || 'configs/mediatek/mt7988a/bpi-r4' }}

jobs:
  check_commits:
    name: Check Commits
    runs-on: ubuntu-24.04
    outputs:
      latest_commit_sha: ${{ steps.get_sha.outputs.latest_commit_sha }}
    steps:
      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}

      - name: Get the latest commit SHA
        id: get_sha
        run: |
          echo "latest_commit_sha=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "latest_commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  build:
    name: Build BPI-R4 with MTK feed
    needs: [check_commits]
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget curl zstd \
            git

      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}

      - name: Clone OpenWrt
        run: |
          git clone ${{ env.OPENWRT_REPOSITORY }} openwrt;
          cd openwrt;
          git checkout ${{ env.OPENWRT_REF }}

      - name: Clone mediatek feed
        run: |
          git clone ${{ env.MEDIATEK_REPOSITORY }} mtk-openwrt-feeds;
          cd mtk-openwrt-feeds;
          git checkout ${{ env.MEDIATEK_REF }}

      - name: Change autobuild rules - important
        run: |
          cd openwrt;
          cp ../my_files/rules ../mtk-openwrt-feeds/autobuild/unified

      - name: Change wireless regdb - optional
        run: |
          cd openwrt;
          rm -rf package/firmware/wireless-regdb/patches;
          rm -rf ..//mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/files/package/firmware/wireless-regdb/patches;
          mkdir -p package/firmware/wireless-regdb/patches;
          mkdir -p ../mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/files/package/firmware/wireless-regdb/patches;
          cp ../my_files/500-tx_power.patch ../mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/files/package/firmware/wireless-regdb/patches
          cp ../my_files/regdb.Makefile package/firmware/wireless-regdb/Makefile

      - name: Copy woziwrt patches
        run: |
          cd openwrt;
          cp ../my_files/{/mt7988a-rfb-spim-nand-nmbm.dtso,mt7981-rfb-spim-nor.dtso,mt7988d-rfb.dts,mt7988a-rfb-spidev.dtso} \
              target/linux/mediatek/files-6.6/arch/arm64/boot/dts/mediatek/

          # cp ../my_files/750-mtk-eth-add-jumbo-frame-support-mt7998.patch target/linux/mediatek/patches-6.6
          # cp ../my_files/0001-mt76-w-package-makefile.patch ../mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/patches-base/0001-mt76-package-makefile.patch
          # cp ../my_files/0004-mac80211-w-package-makefile.patch ../mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/patches-base/0004-mac80211-package-makefile.patch

          cp ../my_files/ethtool/Makefile package/network/utils/ethtool/Makefile
          # cp -r ../my_files/0008-wozi-mac80211-Support-EHT-1024-aggregation-size-in-T.patch ../mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/files/package/kernel/mac80211/patches/subsys/0008-wifi-mac80211-Support-EHT-1024-aggregation-size-in-T.patch
          # cp -r ../my_files/0008-wozi-mac80211-Support-EHT-1024-aggregation-size-in-T.patch ../mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7988_wifi7_mac80211_mlo/package/kernel/mac80211/patches/subsys/0008-wifi-mac80211-Support-EHT-1024-aggregation-size-in-T.patch
          cp ../my_files/999-2709-net-ethernet-mtk_eth_soc-add-rss-lro-reg.patch ../mtk-openwrt-feeds/autobuild/unified/global/24.10/files/target/linux/mediatek/patches-6.6/
          cp ../my_files/999-2710-net-ethernet-mtk_eth_soc-add-rss-support.patch ../mtk-openwrt-feeds/autobuild/unified/global/24.10/files/target/linux/mediatek/patches-6.6/
          cp ../my_files/0006-arch-arm64-dts-mt7988a-add-adma-intrrupts.patch ../mtk-openwrt-feeds/autobuild/unified/global/24.10/patches-base/

          cp -r ../my_files/mediatek/*.* ../mtk-openwrt-feeds/autobuild/unified/global/24.10/files/target/linux/mediatek/files-6.6/drivers/net/ethernet/mediatek/

      - name: Make sed
        run: |
          sed -i 's/CONFIG_PACKAGE_perf=y/# CONFIG_PACKAGE_perf is not set/' \
              ./mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/defconfig \
              ./mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7988_wifi7_mac80211_mlo/.config \
              ./mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7986_mac80211/.config

          sed -i 's/CONFIG_PACKAGE_kmod-thermal=y/# CONFIG_PACKAGE_kmod-thermal is not set/' \
              ./mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7988_wifi7_mac80211_mlo/.config \
              ./mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7981_mac80211/.config \
              ./mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7986_mac80211/.config

      - name: Add patch for wifi power
        run: |
          cd openwrt;
          mkdir -p package/kernel/mt76/patches
          curl -SL https://github.com/openwrt/mt76/commit/8088940ffd047a6d282a95af829562e8038f5b2d.patch | tee package/kernel/mt76/patches/0077-Yukariin-fix-wifi-power.patch

      - name: Run build script
        run: |
          cd openwrt;
          bash -x ../mtk-openwrt-feeds/autobuild/unified/autobuild.sh filogic-mac80211-bpi-r4 log_file=make || true

      - name: Compress all packages
        run: |
          cd openwrt;
          tar caf bin/targets/mediatek/filogic/packages.tar.gz bin/targets/mediatek/filogic/packages

      - name: Add config file
        run: |
          cd openwrt;
          cp .config  bin/targets/mediatek/filogic/config-full

      - name: Package output
        run: |
          cd openwrt;
          tar -cvf ../bpi_r4-images.tar bin/targets/mediatek/filogic

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bpi_r4-images
          path: bpi_r4-images.tar

  release:
    name: Create release
    needs: [build, check_commits]
    if: needs.build.result == 'success'
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bpi_r4-images

      - name: Extract artifacts
        run: tar xf bpi_r4-images.tar

      - name: Get current date
        run: echo "RELEASE_DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@master
        with:
          files: bin/targets/mediatek/filogic/*
          tag_name: ${{ env.RELEASE_PREFIX }}-${{ env.REMOTE_BRANCH }}-${{ env.RELEASE_DATE }}
          name: OpenWRT BPI-R4 with MTK Feed ${{ inputs.DEVICE_CONFIG == 'poe' && 'POE' || '' }} - ${{ env.RELEASE_DATE }}
          body: |
            Updated prebuilt images for BPI-R4 ${{ inputs.DEVICE_CONFIG == 'poe' && 'PoE version' || '' }}  with MTK feed.

            OpenWrt ref: ${{ env.OPENWRT_REF }}
            Mediatek feed ref: ${{ env.MEDIATEK_REF }}
            Project ref: ${{ needs.check_commits.outputs.latest_commit_sha }}

      - name: Clean up old releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 5
          delete_tags: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
